In [38]:
import numpy as np

In [39]:
oneDim = np.array([1,2,3])


In [40]:
print(type(oneDim))

<class 'numpy.ndarray'>


In [41]:
twoDim = np.array([[1,2,3],
                  [4,5,6]])


In [42]:
threeDim = np.array([[
        [1,2,3],
        [4,5,6]],
        [[7,8,9],
        [10,11,12]
    ]])


# Attributes

In [43]:
#1 dim
oneDim.shape, oneDim.ndim, oneDim.dtype, oneDim.size, type(oneDim)

((3,), 1, dtype('int32'), 3, numpy.ndarray)

In [44]:
#2 dim
twoDim.shape, twoDim.ndim, twoDim.dtype, twoDim.size, type(twoDim)

((2, 3), 2, dtype('int32'), 6, numpy.ndarray)

In [45]:
#3 dim
threeDim.shape, threeDim.ndim, threeDim.dtype, threeDim.size, type(threeDim)

((2, 2, 3), 3, dtype('int32'), 12, numpy.ndarray)

# Array Creation

In [46]:
import pandas as pd

In [48]:
dataFrame = pd.DataFrame(twoDim)

In [49]:
dataFrame

0  1  2
0  1  2  3
1  4  5  6

In [55]:
jedynki = np.ones((10,2))
jedynki

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [59]:
zera = np.zeros((7,2,3))
zera

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [60]:
range_array = np.arange(0,100,3)
range_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

# Random

In [73]:
random_array = np.random.randint(0, 10, size=(7,2))
random_array

array([[4, 3],
       [0, 3],
       [5, 0],
       [2, 3],
       [8, 1],
       [3, 3],
       [3, 7]])

In [74]:
float_random_array = np.random.random((3,5))
float_random_array

array([[0.63992102, 0.14335329, 0.94466892, 0.52184832, 0.41466194],
       [0.26455561, 0.77423369, 0.45615033, 0.56843395, 0.0187898 ],
       [0.6176355 , 0.61209572, 0.616934  , 0.94374808, 0.6818203 ]])

In [75]:
np.random.seed(seed = 0)
random_array2 = np.random.randint(0,10,size=(4,6))
random_array2 

array([[5, 0, 3, 3, 7, 9],
       [3, 5, 2, 4, 7, 6],
       [8, 8, 1, 6, 7, 7],
       [8, 1, 5, 9, 8, 9]])

In [78]:
numbers = np.random.randint(1,10, size=(3,7))
print(numbers)

[[4 6 5 5 7 5 5]
 [4 5 5 9 5 4 8]
 [6 6 1 2 6 4 1]]


In [79]:
np.unique(numbers)

array([1, 2, 4, 5, 6, 7, 8, 9])

In [81]:
numbers[0]

array([4, 6, 5, 5, 7, 5, 5])

In [82]:
numbers[:2]

array([[4, 6, 5, 5, 7, 5, 5],
       [4, 5, 5, 9, 5, 4, 8]])

In [91]:
numbers[:1,:2]

array([[4, 6]])

In [94]:
r_array = np.random.randint(0,10, size=(3,5))
ones = np.ones((3,5))
r_array,ones

(array([[8, 2, 3, 0, 0],
        [6, 0, 6, 3, 3],
        [8, 8, 8, 2, 3]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [95]:
print(r_array+ones)

[[9. 3. 4. 1. 1.]
 [7. 1. 7. 4. 4.]
 [9. 9. 9. 3. 4.]]


In [96]:
ones_shape5_3 = np.ones((5,3))
print(r_array+ones_shape5_3)

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

# Shape error

In [97]:
# Need to transpose

In [98]:
new_ones = np.ones((3,5))
r_array - ones

array([[ 7.,  1.,  2., -1., -1.],
       [ 5., -1.,  5.,  2.,  2.],
       [ 7.,  7.,  7.,  1.,  2.]])

In [101]:
r_array * new_ones

array([[8., 2., 3., 0., 0.],
       [6., 0., 6., 3., 3.],
       [8., 8., 8., 2., 3.]])

In [102]:
r_array ** 2

array([[64,  4,  9,  0,  0],
       [36,  0, 36,  9,  9],
       [64, 64, 64,  4,  9]], dtype=int32)

In [103]:
np.square(r_array)

array([[64,  4,  9,  0,  0],
       [36,  0, 36,  9,  9],
       [64, 64, 64,  4,  9]], dtype=int32)

In [104]:
np.mean(r_array)

4.0

In [105]:
np.max(r_array)

8

In [106]:
np.min(r_array)

0

In [107]:
r_array.shape

(3, 5)

In [108]:
r_array.reshape(3,5,1)

array([[[8],
        [2],
        [3],
        [0],
        [0]],

       [[6],
        [0],
        [6],
        [3],
        [3]],

       [[8],
        [8],
        [8],
        [2],
        [3]]])

In [111]:
r_array

array([[8, 2, 3, 0, 0],
       [6, 0, 6, 3, 3],
       [8, 8, 8, 2, 3]])

In [112]:
r_array.T

array([[8, 6, 8],
       [2, 0, 8],
       [3, 6, 8],
       [0, 3, 2],
       [0, 3, 3]])

In [113]:
a1 = np.random.randint(0,10, size=(3,3))
a2 = np.random.randint(0,10, size=(3,2))
a1,a2

(array([[2, 0, 8],
        [8, 3, 8],
        [2, 8, 4]]),
 array([[3, 0],
        [4, 3],
        [6, 9]]))

In [114]:
np.dot(a1,a2)

array([[54, 72],
       [84, 81],
       [62, 60]])

In [115]:
a3 = np.random.randint(0,10, size=(4,3))
a4 = np.random.randint(0,10, size=(4,3))
np.dot(a3,a4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

# Shape error

In [116]:
np.dot(a3,a4.T)

array([[ 72, 104, 136,  64],
       [ 36,  75, 112,  82],
       [ 69, 119, 165,  96],
       [ 76,  79, 104,  62]])

In [118]:
a1 = np.random.randint(0,10, size=(3,2))
a2 = np.random.randint(0,10, size=(3,2))
a1,a2,a1>a2

(array([[5, 7],
        [0, 8],
        [4, 6]]),
 array([[5, 8],
        [2, 3],
        [9, 7]]),
 array([[False, False],
        [False,  True],
        [False, False]]))

In [119]:
a1 >= a2

array([[ True, False],
       [False,  True],
       [False, False]])

In [120]:
a1 > 7

array([[False, False],
       [False,  True],
       [False, False]])

In [121]:
a1 == a2

array([[ True, False],
       [False, False],
       [False, False]])

In [122]:
np.sort(a1)

array([[5, 7],
       [0, 8],
       [4, 6]])

In [127]:
array = np.random.randint(0,10, size= (6,5))
array

array([[1, 9, 5, 9, 9],
       [2, 0, 9, 1, 9],
       [0, 6, 0, 4, 8],
       [4, 3, 3, 8, 8],
       [7, 0, 3, 8, 7],
       [7, 1, 8, 4, 7]])

In [128]:
np.sort(array)

array([[1, 5, 9, 9, 9],
       [0, 1, 2, 9, 9],
       [0, 0, 4, 6, 8],
       [3, 3, 4, 8, 8],
       [0, 3, 7, 7, 8],
       [1, 4, 7, 7, 8]])

In [129]:
np.argsort(array)

array([[0, 2, 1, 3, 4],
       [1, 3, 0, 2, 4],
       [0, 2, 3, 1, 4],
       [1, 2, 0, 3, 4],
       [1, 2, 0, 4, 3],
       [1, 3, 0, 4, 2]], dtype=int64)

In [130]:
np.argmax(array)

1

In [133]:
np.argmin(array)

6

In [141]:
np.argmax(array, axis=1)

array([1, 2, 4, 3, 3, 2], dtype=int64)

In [140]:
np.argmin(array, axis=0)

array([2, 1, 2, 1, 4], dtype=int64)

In [142]:
np.random.randn(3, 5)

array([[-1.03424284,  0.68159452, -0.80340966, -0.68954978, -0.4555325 ],
       [ 0.01747916, -0.35399391, -1.37495129, -0.6436184 , -2.22340315],
       [ 0.62523145, -1.60205766, -1.10438334,  0.05216508, -0.739563  ]])

In [143]:
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])